name: aura_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+3

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  camera: ^0.10.5+9
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.0
  firebase_auth: ^5.5.0
  video_player: ^2.8.2
  firebase_storage: ^12.4.0
  path: ^1.9.0
  video_thumbnail: ^0.5.3
  image_picker: ^1.1.2
  share_plus: ^10.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/power-music-concept-portrait (2).jpg
    - assets/images/logo_1stdraft_forapp (1).png
    - assets/images/aura star logo.png
    - assets/images/Aura star level container.png
    - assets/images/level analysis banner.png
    - assets/images/bar.png
    - assets/images/live.png
    - assets/images/bottle.png
    - assets/images/Flip a coin image.png
    - assets/images/pepsi.png
    - assets/images/Nike.png
    - assets/images/H&M.png
    - assets/images/Explore brand(clickable button).png
    - assets/images/creator image.png
    - assets/images/menu container.png
    - assets/images/A.png
    - assets/images/Home.png
    - assets/images/challenge.png
    - assets/images/Leaderboard.png
    - assets/images/user.png
    - assets/images/Live challenge Image container.png
