name: aura_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+5

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  camera: ^0.10.5+9
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.0
  firebase_auth: ^5.5.0
  video_player: ^2.8.2
  firebase_storage: ^12.4.0
  path: ^1.9.0
  video_thumbnail: ^0.5.3
  image_picker: ^1.1.2
  share_plus: ^10.0.0
  app_links: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/power-music-concept-portrait (2).jpg
    - assets/images/Aura arena.png
    - assets/images/Aura Arena Mono.png
    - assets/images/level analysis banner.png
    - assets/images/bar.png
    - assets/images/live.png
    - assets/images/bottle.png
    - assets/images/Flip a coin image.png
    - assets/images/pepsi.png
    - assets/images/Nike.png
    - assets/images/H&M.png
    - assets/images/Explore brand(clickable button).png
    - assets/images/creator image.png
    - assets/images/menu container.png
    - assets/images/Home.png
    - assets/images/challenge.png
    - assets/images/Leaderboard.png
    - assets/images/user.png
    - assets/images/Live challenge Image container.png
    - assets/images/Splash screen/BG.png
    - assets/images/Splash screen/bg 2.png
    - assets/images/Splash screen/Aura arena.png
    - assets/images/Splash screen/logo.png
    - assets/images/Splash screen/Play score flex.png
    - assets/images/Splash screen/Star icon.png
    - assets/images/Splash screen/Orb.png
    - assets/images/Splash screen/Charging your aura.png
    - assets/images/Splash screen/See It. Copy It. Slay It.png
    - assets/images/Splash screen/Copy the challenge as close as you can.png
    - assets/images/Splash screen/ICON.png
    - assets/images/Splash screen/On page scroll icon.png
    - assets/images/Splash screen/Grey scroll icon.png
    - assets/images/Splash screen/BG 3.png
    - assets/images/Splash screen/bg 4.png
    - assets/images/Splash screen/Crown.png
    - assets/images/Splash screen/Star icon 2.png
    - assets/images/Splash screen/headline.png
    - assets/images/Splash screen/headline 2.png
    - assets/images/Splash screen/Subhead.png
    - assets/images/Splash screen/subtext.png
    - assets/images/Splash screen/button.png
    - assets/images/Splash screen/start text.png
    - assets/images/Splash screen/Double lines.png
